//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efdb_arac_kiralama_proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araclar()
        {
            this.Kiralamalars = new HashSet<Kiralamalar>();
        }
    
        public int AracNo { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yil { get; set; }
        public string Renk { get; set; }
        public string Plaka { get; set; }
        public Nullable<decimal> GunlukUcret { get; set; }
        public string Durum { get; set; }
        public Nullable<int> MarkaNo { get; set; }
        public string ResimYolu { get; set; }
    
        public virtual Markalar Markalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kiralamalar> Kiralamalars { get; set; }
    }
}
