//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efdb_arac_kiralama_proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kiralamalar
    {
        public int KiralamaNo { get; set; }
        public Nullable<int> MusteriNo { get; set; }
        public Nullable<int> AracNo { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
